version: '3.8'

services:
#  mysql:
#    image: mysql:latest
#    container_name: mysql_db
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: inventory_db
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
#  mysql_data:
  mongo_data:
