# version: '3.8'
services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
#      - inventory-service
      - product-catalog-service

#  inventory-service:
#    build: ./inventory-service
#    ports:
#      - "8082:8082"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/inventory_db
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=root
#    depends_on:
#      - mysql

  product-catalog-service:
    build: ./product-catalog-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/products
#    depends_on:
#      - mongo
